version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - 'gruffalinas-pgsql:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
  # typesense:
  #     image: typesense/typesense:0.25.2
  #     restart: on-failure
  #     ports:
  #       - "8108:8108"
  #     volumes:
  #       - ./typesense-data:/data
  #     command: '--data-dir /data --api-key=xyz --enable-cors'
volumes:
    gruffalinas-pgsql:
        driver: local
